// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import ()

type Meeting struct {
	ID     int32  `json:"id"`
	InTime string `json:"in_time"`
	InMeet bool   `json:"in_meet"`
}
